name: Record
description: Performs functional tests checks
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
    - uses: bahmutov/npm-install@v1
    - run: npx playwright install-deps
      shell: sh
    - run: npx playwright install
      shell: sh
    - run: npx @replayio/playwright install
      shell: sh
    - run: npm run build
      shell: sh
    - name: test
      run: npm run test:replay
      shell: sh
      env:
        RECORD_REPLAY_WEBHOOK_URL: ${{ secrets.RECORD_REPLAY_WEBHOOK_URL }}
        RECORD_REPLAY_TEST_METRICS: 1
    - name: Upload replays
      if: ${{ always() }}
      uses: replayio/action-upload@v0.4.3
      with:
        api-key: rwk_uGZ2699gqfSQB5klt3Wpa8TtkdYHg4ZjvWRZ8RIZqdc
        public: true