name: Functional
description: Performs functional tests checks
inputs:
  project:
    required: true
    description: "Playwright Project Name"
  apiKey:
    required: true
    description: "Replay.io API Key"
  issue-number:
    required: true
    description: "Issue / Pull Request on which to comment results"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
    - uses: bahmutov/npm-install@v1
    - run: npx playwright install-deps
      shell: sh
    - run: npx playwright install
      shell: sh
    - run: npm run build
      shell: sh
    - uses: replayio/action-playwright@v0.4.17
      with:
        command: npx playwright test packages/dom/test/functional
        apiKey: ${{ inputs.apiKey }}
        issue-number: ${{ inputs.issue-number }}
        project: ${{ inputs.project }}
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: visual-snapshots-diff
        path: test-results
