name: Tests
on: [push, pull_request]

jobs:
  functional-tests:
    name: Functional tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/functional
