name: Tests
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      project:
        required: false
        default: "replay-firefox"
        description: "Playwright Project Name"

jobs:
  # checks:
  #   name: Linting and type checking
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ./.github/actions/setup
  #     - uses: ./.github/actions/typescript

  # unit-tests:
  #   name: Unit tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ./.github/actions/setup
  #     - uses: ./.github/actions/unit

  functional-tests:
    name: Functional tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/functional
        with:
          project: replay-firefox
          apiKey: ${{ secrets.RECORD_REPLAY_API_KEY }}
          issue-number: ${{ github.event.pull_request.number }}
